/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-south-1",
  aws_cognito_identity_pool_id:
    "ap-south-1:490abe33-9f12-417d-ab9f-14a93696591a",
  aws_cognito_region: "ap-south-1",
  aws_user_pools_id: "ap-south-1_y9Isuh4e6",
  aws_user_pools_web_client_id: "42mq6lieil6nkkp40c8njsle1v",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL", "NAME"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_user_files_s3_bucket:
    "scholalifyc2829de80a324afea693340c06ea042c52647-prod",
  aws_user_files_s3_bucket_region: "ap-south-1",
};

export default awsmobile;
